# Generated by Django 3.0.3 on 2020-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=256)),
            ],
        ),
    ]
