# Generated by Django 3.0.3 on 2020-04-23 03:56

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('googleplaces', '0003_auto_20200422_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=djgeojson.fields.PointField(),
        ),
    ]
