# Generated by Django 3.0.3 on 2020-04-24 04:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('googleplaces', '0004_auto_20200422_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
