# Generated by Django 3.0.3 on 2020-04-24 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('googleplaces', '0005_location_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='loc_id',
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
