# Generated by Django 3.0.3 on 2020-04-24 23:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('googleplaces', '0006_auto_20200424_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
